<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Wed, 22 Nov 2017 09:06:43 +0000
 */

$conf['title'] = 'Wiki GalaxyHopes';
$conf['lang'] = 'ru';
$conf['license'] = '0';
$conf['breadcrumbs'] = 0;
$conf['showuseras'] = 'username';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
